export const FETCH_POSTS = 'FETCH_POSTS';
export const NEW_POSTS = 'NEW_POSTS';
export const UPDATE_POSTS = 'UPDATE_POSTS';
export const FETCH_MOCK_POSTS = 'FETCH_MOCK_POSTS';
export const WELCOME_MODAL_OPEN = 'WELCOME_MODAL_OPEN';
export const HIDE_COOKIES = 'HIDE_COOKIES';